soun_buzz:
    resource: "@SoundBuzzBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


soundbuzz_homepage:
    path: /
    defaults: { _controller: SoundBuzzBundle:Default:index }

#PROFIL
soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getProfil }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

soundbuzz_updateprofil:
    path: /profil/update/{id}
    defaults: { _controller: SoundBuzzBundle:User:updateprofil }

soundbuzz_deleteuser:
    path:     /profil/delete/{id}
    defaults: { _controller:SoundBuzzBundle:User:deleteuser }
#TRACK
track_new:
    path: /trackUpload
    defaults: { _controller: SoundBuzzBundle:Track:uploadTrack }

track_index:
    path: /tracks
    defaults: { _controller: SoundBuzzBundle:Track:index }

track_information:
    path: /tracks/{id}
    defaults: { _controller: SoundBuzzBundle:Track:getTrack }

track_edit:
    path: /tracks/{id}/edit
    defaults: { _controller: SoundBuzzBundle:Track:edit }

track_delete:
    path: /tracks/{id}/delete
    defaults: { _controller: SoundBuzzBundle:Track:delete }

playlists_display:
    path: /playlists
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylist }

playlists_display_songs:
    path: /playlists_songs
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylistSongs }