soun_buzz:
    resource: "@SoundBuzzBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

soundbuzz_homepage:
    path: /
    defaults: { _controller: SoundBuzzBundle:Default:index }

### USER ###
soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getProfil }

soundbuzz_updateprofil:
    path: /profil/update/{id}
    defaults: { _controller: SoundBuzzBundle:User:updateprofil }

soundbuzz_deleteuser:
    path:     /profil/delete/{id}
    defaults: { _controller:SoundBuzzBundle:User:deleteuser }

### EASYADMIN ###
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

### TRACK ###
track_new:
    path: /trackUpload
    defaults: { _controller: SoundBuzzBundle:Track:uploadTrack }

track_index:
    path: /tracks
    defaults: { _controller: SoundBuzzBundle:Track:index }

track_alltracks:
    path: /AllTracks
    defaults: { _controller: SoundBuzzBundle:Track:getAllTracks }

track_information:
    path: /tracks/{id}
    defaults: { _controller: SoundBuzzBundle:Track:getTrack }

track_edit:
    path: /tracks/{id}/edit
    defaults: { _controller: SoundBuzzBundle:Track:edit }

track_delete:
    path: /tracks/{id}/delete
    defaults: { _controller: SoundBuzzBundle:Track:delete }

dl_track:
    path: /tracks/{id}/download
    defaults: { _controller: SoundBuzzBundle:Track:download }

### PLAYLIST ###
playlist_index:
    path: /playlists
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylist }

playlist_information:
    path: /playlists/{id}
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylistSongs }
    requirements:
        id: '\d+'

playlist_add:
    path: /playlists/add
    defaults: { _controller: SoundBuzzBundle:Playlist:addPlaylist }

### LIKE ###
like_track:
    path: /has-liked/{id}
    defaults: { _controller: SoundBuzzBundle:Track:like }
