soun_buzz:
    resource: "@SoundBuzzBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getProfil }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

#TRACK
track_new:
    path: /trackUpload
    defaults: { _controller: SoundBuzzBundle:Track:uploadTrack }

track_index:
    path: /tracks
    defaults: { _controller: SoundBuzzBundle:Track:index }
