soun_buzz:
    resource: "@SoundBuzzBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

soundbuzz_homepage:
    path: /
    defaults: { _controller: SoundBuzzBundle:Default:index }

### EASYADMIN ###
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

### USER ###
soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getProfil }

soundbuzz_updateprofil:
    path: /profil/update/{id}
    defaults: { _controller: SoundBuzzBundle:User:updateprofil }

soundbuzz_deleteuser:
    path:     /profil/delete/{id}
    defaults: { _controller:SoundBuzzBundle:User:deleteuser }

### TRACK ###
track_new:
    path: /trackUpload
    defaults: { _controller: SoundBuzzBundle:Track:uploadTrack }

track_index:
    path: /tracks
    defaults: { _controller: SoundBuzzBundle:Track:index }

track_alltracks:
    path: /AllTracks
    defaults: { _controller: SoundBuzzBundle:Track:getAllTracks }

track_alltrack:
    path: /AllTrack
    defaults: { _controller: SoundBuzzBundle:Track:getAllTracksConec }

track_information:
    path: /tracks/{id}
    defaults: { _controller: SoundBuzzBundle:Track:getTrack }

track_edit:
    path: /tracks/{id}/edit
    defaults: { _controller: SoundBuzzBundle:Track:edit }

track_delete:
    path: /tracks/{id}/delete
    defaults: { _controller: SoundBuzzBundle:Track:delete }

dl_track:
    path: /tracks/{id}/download
    defaults: { _controller: SoundBuzzBundle:Track:download }

liked_tracks:
    path: /liked-tracks
    defaults: { _controller: SoundBuzzBundle:Track:getLikedTracks }

### PLAYLIST ###
playlist_allplaylists:
    path: /AllPlaylists
    defaults: { _controller: SoundBuzzBundle:Playlist:getAllPlaylists }

playlist_allplaylist:
    path: /AllPlaylist
    defaults: { _controller: SoundBuzzBundle:Playlist:getAllPlaylistsConec }

playlist_index:
    path: /playlists
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylist }

playlist_information:
    path: /playlists/{id}
    defaults: { _controller: SoundBuzzBundle:Playlist:userPlaylistSongs }
    requirements:
        id: '\d+'

playlist_add:
    path: /playlists/add
    defaults: { _controller: SoundBuzzBundle:Playlist:addPlaylist }
    
playlist_add_tracks:
    path: /playlists/{id}/add-tracks
    defaults: { _controller: SoundBuzzBundle:Playlist:addTracks }
    requirements:
        id: '\d+'

playlist_add_tracks_track_added:
    path: /playlists/{id}/add-tracks/{trackId}
    defaults: { _controller: SoundBuzzBundle:Playlist:trackAdded }
    requirements:
        id: '\d+'
        trackId: '\d+'

### LIKE ###
like_track:
    path: /has-liked/{id}
    defaults: { _controller: SoundBuzzBundle:Track:like }

### GENRE ###
track_by_genre:
    path: /genre/{id}
    defaults: { _controller: SoundBuzzBundle:Track:getTrackByGenre }