soundbuzz_homepage:
    path: /
    default: { _controller: SoundBuzzBundle:Default:index }

soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getprofil }

soundbuzz_profil:
    path: /profil/{id}/playlists
    defaults: { _controller: SoundBuzzBundle:User:getplaylists }