soundbuzz_homepage:
    path: /
    default: { _controller: SoundBuzzBundle:Default:index }

soundbuzz_profil:
    path: /profil/{id}
    defaults: { _controller: SoundBuzzBundle:User:getprofil }

soundbuzz_updateprofil:
    path: /profil/update/{id}
    defaults: { _controller: SoundBuzzBundle:User:updateprofil }